spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/kafka_account
    username: kafka_admin
    password: kafka12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080